# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [46]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7702, 0.3761, 0.3866],
        [0.1406, 0.6770, 0.0749],
        [0.4225, 0.6156, 0.1641],
        [0.6320, 0.1814, 0.0829],
        [0.7488, 0.2152, 0.5652]])


Get its size

In [47]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [48]:
x[1:3] = 2
print(x)

tensor([[0.7702, 0.3761, 0.3866],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.6320, 0.1814, 0.0829],
        [0.7488, 0.2152, 0.5652]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [49]:
t = torch.ByteTensor(size=(5,))
t[1:4]=1

In [50]:
# 1. uninitialized tensor with size (2,17)
t = torch.Tensor(2,17)
print('1. uninitialized tensor with size (2,17):',t)
print('--------------')

# 2. randomly intialized tensor with size (3,1)
t = torch.FloatTensor(3,1)
print('2. randomly intialized tensor with size (3,1):', t)
print('--------------')

# 3. 64-bit integer (long) tensor with size (5,2,1)
t = torch.LongTensor(5,2,1)
t[:] = 7
print('3. 64-bit integer (signed) tensor with size (5,2,1):', t)
print('--------------')

# 4.
t = torch.ByteTensor(size=(5,))
t[1:4]=1
print('3. 8-bit integer (unsigned) tensor with size (5,):', t)
print('--------------')


1. uninitialized tensor with size (2,17): tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  4.7157e-31,  1.4013e-45,
         -3.2512e-19,  4.5841e-41]])
--------------
2. randomly intialized tensor with size (3,1): tensor([[0.0000e+00],
        [0.0000e+00],
        [1.4253e-30]])
--------------
3. 64-bit integer (signed) tensor with size (5,2,1): tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
--------------
3. 8-bit integer (unsigned) tensor with size (5,): tensor([96,  1,  1,  1,  1],

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [51]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.3736, 0.9655, 0.8387],
        [2.2988, 2.0071, 2.0853],
        [2.5873, 2.7761, 2.6753],
        [1.1999, 0.6982, 1.0567],
        [0.8833, 0.4368, 0.5721]])


### 2.2 Addition: syntax 2

In [52]:
print(torch.add(x, y))

tensor([[1.3736, 0.9655, 0.8387],
        [2.2988, 2.0071, 2.0853],
        [2.5873, 2.7761, 2.6753],
        [1.1999, 0.6982, 1.0567],
        [0.8833, 0.4368, 0.5721]])


### 2.3 Addition: giving an output tensor

In [53]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.3736, 0.9655, 0.8387],
        [2.2988, 2.0071, 2.0853],
        [2.5873, 2.7761, 2.6753],
        [1.1999, 0.6982, 1.0567],
        [0.8833, 0.4368, 0.5721]])


### 2.4 Addition: in-place

adds `x`to `y`

In [54]:
y.add_(x)
print(y)

tensor([[1.3736, 0.9655, 0.8387],
        [2.2988, 2.0071, 2.0853],
        [2.5873, 2.7761, 2.6753],
        [1.1999, 0.6982, 1.0567],
        [0.8833, 0.4368, 0.5721]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [55]:
print(x[:, 1])

tensor([0.3761, 2.0000, 2.0000, 0.1814, 0.2152])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [56]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [57]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [58]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [59]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [60]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
